--- 
abstract: A lightweight Crypt/Digest convenience API
author: Yuval Kogman, <nothingmuch@woobling.org>
build_requires: 
  Test::Exception: 0
  Test::More: 0
  Test::use::ok: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Crypt-Util
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Crypt::Blowfish: 0
  Crypt::CBC: 0
  Crypt::CFB: 0
  Crypt::DES: 0
  Crypt::RC6: 0
  Crypt::RIPEMD160: 0
  Crypt::Rijndael: 0
  Crypt::Serpent: 0
  Crypt::Twofish: 0
  Digest::HMAC: 0
  Digest::MD5: 0
  Digest::Whirlpool: 0
requires: 
  Class::Accessor::Fast: 0
  Digest: 0
  Perl6::Junction: 0
  Storable: 0
  Sub::Exporter: 0
version: 0.05
